 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    -QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -1.691E-08 -3.657E+02  2.679E+05  1.711E+06 -1.832E+06  0.000E+00  0.000E+00 -3.095E+06  5.292E+06  0.000E+00  9.900E+05  8.683E+04
 Energy balance for sum of all zone
   0       0.00  -1.691E-08 -3.657E+02  2.679E+05  1.711E+06 -1.832E+06  0.000E+00  0.000E+00 -3.095E+06  5.292E+06  0.000E+00  9.900E+05  8.683E+04
