 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    -QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -1.315E-07 -6.767E+02  7.325E+05  1.181E+06 -1.739E+06  0.000E+00  0.000E+00 -3.799E+06  3.835E+06  0.000E+00  1.978E+06  1.737E+05
 Energy balance for sum of all zone
   0       0.00  -1.315E-07 -6.767E+02  7.325E+05  1.181E+06 -1.739E+06  0.000E+00  0.000E+00 -3.799E+06  3.835E+06  0.000E+00  1.978E+06  1.737E+05
